/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'learningPathCreation': MotiaStream<{ stage: 'analyzing' | 'researching' | 'generating' | 'enriching' | 'completed' | 'error'; message: string; progress: number; data?: unknown; timestamp?: number }>
  }

  interface Handlers {
    'SaveLearningPath': EventHandler<never, never>
    'GetUserLearningPaths': ApiRouteHandler<{}, unknown, never>
    'GetLearningPathDetails': ApiRouteHandler<{}, unknown, never>
    'CreateLearningPath': ApiRouteHandler<{ topic: string; background: string; goalLevel: 'beginner' | 'intermediate' | 'advanced'; preferences?: { includeVideos: boolean; includeArticles: boolean; includeDocs: boolean; languages: Array<string> } }, unknown, { topic: 'learning.path.requested'; data: never }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'RegisterUser': ApiRouteHandler<{ name: string; email: string; password: string }, unknown, never>
    'GetCurrentUser': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'LoginUser': ApiRouteHandler<{ email: string; password: string }, unknown, never>
    'LearningPathGenerator': EventHandler<never, { topic: 'learning.path.generated'; data: never } | { topic: 'learning.path.failed'; data: never }>
  }
}